const IconGrid = ({ className, color }) => {
  return (
    <svg
      width="60"
      height="59"
      viewBox="0 0 60 59"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
    >
      <rect
        x="3"
        y="3"
        width="22"
        height="22"
        rx="4"
        className={color}
        strokeOpacity="0.866667"
        strokeWidth="5"
      />
      <rect
        x="3"
        y="34"
        width="22"
        height="22"
        rx="4"
        className={color}
        strokeOpacity="0.866667"
        strokeWidth="5"
      />
      <rect
        x="35"
        y="3"
        width="22"
        height="22"
        rx="4"
        className={color}
        strokeOpacity="0.866667"
        strokeWidth="5"
      />
      <rect
        x="35"
        y="34"
        width="22"
        height="22"
        rx="4"
        className={color}
        strokeOpacity="0.866667"
        strokeWidth="5"
      />
    </svg>
  );
};
export default IconGrid;
