import { Noto_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/layouts/main/header/Header";

const notoSans = Noto_Sans({ subsets: ["latin"], variable: "--font-noto" });

export const metadata = {
  title: "Home - WWM",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={notoSans.className}>
        <Header />
        <main>{children}</main>        
      </body>
    </html>
  );
}
